Spotify
Marvel999/FamousComposeBook pull request #14
Opened 2022-11-21 06:39 UTC by Manish-Marvel

2022-12-01 12:07 UTC, Manish-Marvel commented
@sparrow007 Please Review

2022-12-03 19:55 UTC, sparrow007 commented on app/src/main/AndroidManifest.xml
> +            <meta-data
Please remove this

2022-12-03 19:58 UTC, sparrow007 commented on app/src/main/java/com/marvel999/fuitemplet/Spotify/SpotifyActivity.kt
> +                contentDescription = "spotify Splash screen"
Plesase put these strings in strings.xml

2022-12-03 20:04 UTC, sparrow007 commented on app/src/main/java/com/marvel999/fuitemplet/Spotify/SpotifyHomeActivity.kt
> +                        navController.graph.startDestinationRoute?.let { screen_route ->
Please check if we can remove the navcontroller?

2022-12-03 20:07 UTC, sparrow007 commented on app/src/main/java/com/marvel999/fuitemplet/Spotify/component/RowMusicItem.kt
> +                val color:Color = Color(parseColor(randomHexColorGanrator()))
Please remove explicit data type

2022-12-03 20:12 UTC, sparrow007 commented on app/src/main/java/com/marvel999/fuitemplet/Spotify/screen/SpotifyHome.kt
> +            Spacer(modifier = Modifier.padding(top = 20.dp))
Use height instead of padding

2022-12-03 20:17 UTC, sparrow007 requested changes
Please check all the comments

2022-12-04 10:02 UTC, Marvel999 approved these changes

2022-12-04 10:02 UTC, Marvel999 commented on app/src/main/AndroidManifest.xml
> +            <meta-data
done

2022-12-04 10:02 UTC, Marvel999 commented on app/src/main/java/com/marvel999/fuitemplet/Spotify/SpotifyActivity.kt
> +                contentDescription = "spotify Splash screen"
done

2022-12-04 10:02 UTC, Marvel999 commented on app/src/main/java/com/marvel999/fuitemplet/Spotify/SpotifyHomeActivity.kt
> +                        navController.graph.startDestinationRoute?.let { screen_route ->
it navoptionBuilder scope not navController

2022-12-04 10:02 UTC, Marvel999 commented on app/src/main/java/com/marvel999/fuitemplet/Spotify/component/RowMusicItem.kt
> +                val color:Color = Color(parseColor(randomHexColorGanrator()))
done

2022-12-04 10:02 UTC, Marvel999 commented on app/src/main/java/com/marvel999/fuitemplet/Spotify/screen/SpotifyHome.kt
> +            Spacer(modifier = Modifier.padding(top = 20.dp))
done

2022-12-04 10:10 UTC, merged